#!/bin/bash
# Main installation, provides wireless compatibility, dhcp and DNS resolving, screenshot functionality, audio, a login screen and an app sandbox
doas apk add iwd openresolv sway swaybg grim slurp clipman pipewire pipewire-pulse wireplumber greetd-tuigreet flatpak bubblewrap man-db || exit 1

# Desktop portals, uncomment if you want to be able to use screen sharing
# doas apk add xdg-desktop-portal xdg-desktop-portal-wlr xdg-desktop-portal-gtk

# Kiosk dependencies, uncomment if this is your desired setup. You may also install pipewire and wireplumber manually.
# doas apk add cage cagebreak

doas rm /etc/init.d/alpine-update 2> /dev/null
doas echo '#!/sbin/openrc-run
description="Alpine Linux system updater"

depend() {
  need localmount
  need networking
  need bootmisc
  need iwd
}

start() {
  ebegin "Updating packages to latest version"
  (apk update && apk upgrade) > /dev/null &
  eend $?
}' > /etc/init.d/alpine-update
doas chmod +x /etc/init.d/alpine-update
doas rc-update add alpine-update default

doas rm /etc/init.d/wpa_* 2> /dev/null
doas rm /etc/network/interfaces 2> /dev/null
doas echo 'auto lo
iface lo inet looback' > /etc/network/interfaces

doas rm /etc/iwd/main.conf
doas echo '#[EAP]
#mtu=1400

[General]
EnableNetworkConfiguration=True
#ControlPortOverNL80211=True
#RoamThreshold=-70

[Network]
NameResolvingService=resolvconf

#[Scan]
# DisablePeriodicScan=false
# DisableRoamingScan=false

#[Blacklist]

#[Rank]
# BandModifier5Ghz=1.0' > /etc/iwd/main.conf
doas rc-update add iwd boot

cp .profile ~/
rm .profile

# Not really needed for kiosk operation
doas rm /etc/greetd/config.toml 2> /dev/null
doas mv sway /usr/bin/sway-launch
doas mkdir /etc/greetd
doas echo '[terminal]
vt = 7

[default_session]
command = "tuigreet --cmd sway-run --time"
user = "crow"
' > /etc/greetd/config.toml
