[package]
name = "desktop.d"
version = "0.1.0"
edition = "2024"

[dependencies]
ratatui = "0.26" 
crossterm = "0.27" 
serde = { version = "1.0", features = ["derive"] }
serde_yaml = "0.9"
walkdir = "2.3"
signal-hook = "0.3.17"
