theme = "catppuccin_mocha"

[editor]
mouse = false
cursorline = true
bufferline = "multiple"
true-color = true

[editor.statusline]
mode.normal = "N"
mode.insert = "I"
mode.select = "V"

[editor.cursor-shape]
normal = "block"
insert = "bar"
select = "underline"

[editor.search]
smart-case = true
wrap-around = true

[editor.file-picker]
hidden = false
git-ignore = true
git-global = true
git-exclude = true

[editor.soft-wrap]
enable = false
max-wrap = 25
